name: devel
on:
  pull_request:
  push:
    branches:
    - master
    - staging
    - trying

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build
